### ISSUE TITLE
Class not found crash | Not supported version?

### ISSUE THREAD

**Issue by UltraBlackLinux** [5zig-reborn/The-5zig-Mod#138]
**Describe the bug**
Minecraft is crashing, when trying to use the fabric mod.
Is 1.16 not supported yet? Why? What importand stuff changes between 1.15 and 1.16?

**Logs**
```
java.lang.NoClassDefFoundError: net/minecraft/realms/RealmsSharedConstants
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at Variables.<clinit>(Variables.java:121)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at eu.the5zig.mod.MinecraftFactory.<clinit>(MinecraftFactory.java:32)
    at eu.the5zig.mod.The5zigMod.<clinit>(The5zigMod.java:78)
    at net.minecraft.client.MinecraftClient.handler$zgf000$displayScreen(MinecraftClient:5380)
    at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:579)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.minecraft.realms.RealmsSharedConstants
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 24 more
```

**Desktop (please complete the following information):**
 - OS: Manjaro 5.20.5
 - Version 3.14.0
 - Minecraft 1.16.4, Fabric

**Comment by RoccoDev** [comment]
You can find 1.16 alpha builds here: https://github.com/5zig-reborn/deployments/tree/1.16
