### ISSUE TITLE
Crash when when Account List is empty and "Remove" is clicked

### ISSUE THREAD

**Issue by MalTeeez** [5zig-reborn/The-5zig-Mod#46]
**Describe the bug**
The client crashes when when the account List is empty and "Remove" is clicked

**To Reproduce**
1. Go to the Account List
2. Click on 'Remove'
3. The Game crashes
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at eu.the5zig.mod.gui.GuiAccountManager.actionPerformed(GuiAccountManager.java:93)
	at eu.the5zig.mod.gui.Gui.actionPerformed0(Gui.java:163)
	at eu.the5zig.mod.gui.Gui.mouseClicked0(Gui.java:305)
	at GuiHandle.func_73864_a(GuiHandle.java:84)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:555)
	at GuiHandle.func_146274_d(GuiHandle.java:68)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Expected behavior**
A warning message should pop up informing the user that the list is already empty.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 13.0

**Comment by RoccoDev** [comment]
Minecraft version?

**Comment by MalTeeez** [comment]
1.8.9
