### ISSUE TITLE
iTunes Module

### ISSUE THREAD

**Issue by mendel3** [5zig-reborn/The-5zig-Mod#66]
**Describe the bug**
The iTunes Module doesn't show up (I believe the issue is that com/jacob/com/Dispatch is missing)

**To Reproduce**
1. Enable the iTunes module
2. Open the iTunes application
3. It doesn't show up
4. Errors spammed in fml-client-latest

**Expected behavior**
The iTunes module to show up
**Screenshots**
![image](https://user-images.githubusercontent.com/15878726/81751389-2d8bd280-9464-11ea-9473-81ab0edc4e8d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Version 3.14.0

**Additional context**
The full log spam is:
`[15:14:31] [Async Executor Pool #2155/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: com/jacob/com/Dispatch
[15:14:31] [Async Executor Pool #2155/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at eu.the5zig.mod.manager.itunes.ITunesWindowsDelegate$2.run(ITunesWindowsDelegate.java:108)
[15:14:31] [Async Executor Pool #2155/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:14:31] [Async Executor Pool #2155/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:14:31] [Async Executor Pool #2155/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)
[15:14:31] [Async Executor Pool #2155/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: com.jacob.com.Dispatch
[15:14:31] [Async Executor Pool #2155/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[15:14:31] [Async Executor Pool #2155/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[15:14:31] [Async Executor Pool #2155/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[15:14:31] [Async Executor Pool #2155/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more`

**Comment by mendel3** [comment]
A different related iTunes error is
`[15:25:03] [Async Executor Pool #4850/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at eu.the5zig.mod.manager.itunes.ITunesWindowsDelegate$2.run(ITunesWindowsDelegate.java:108)
[15:25:03] [Async Executor Pool #4850/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:25:03] [Async Executor Pool #4850/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:25:03] [Async Executor Pool #4850/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)
[15:25:03] [Async Executor Pool #4850/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: com.jacob.com.Dispatch
[15:25:03] [Async Executor Pool #4850/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[15:25:03] [Async Executor Pool #4850/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[15:25:03] [Async Executor Pool #4850/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[15:25:03] [Async Executor Pool #4850/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more`
